/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Clorio Data API
 * OpenAPI spec version: 1.0.0
 */
import type { GetHealthEpoch } from './getHealthEpoch';
import type { GetHealthSlot } from './getHealthSlot';

export interface GetHealth {
  status: string;
  db: string;
  blockchainLength: number;
  syncStatus: string;
  chainId: string;
  epoch: GetHealthEpoch;
  slot: GetHealthSlot;
}
